<?php

$SETTINGS = array();

$SETTINGS['0'] = "";
$SETTINGS['13'] = "";
$SETTINGS['COMPANY_NAME'] = "Draw It To Know It";
$SETTINGS['COMPANY_LEGAL_NAME'] = "Draw It To Know It, LLC";
$SETTINGS['COMPANY_ADDRESS_1'] = "6507 Ferguson Street";
$SETTINGS['COMPANY_ADDRESS_2'] = "Suite 102";
$SETTINGS['COMPANY_CITY_STATE_ZIP'] = "Indianapolis, Indiana 46260";
$SETTINGS['COMPANY_TELEPHONE'] = "317-446-3006";
$SETTINGS['COMPANY_DOMAIN'] = "drawittoknowit.com";
$SETTINGS['COMPANY_URL'] = "http://www.drawittoknowit.com";
$SETTINGS['FREE_DEMO_PRODUCT'] = "15";
$SETTINGS['EXTENDED_DEMO_PRODUCT'] = "14";
$SETTINGS['SHARE_THIS_CODE'] = "<span  class='st_twitter' ></span><span  class='st_facebook' ></span><span  class='st_linkedin' ></span><span  class='st_digg' ></span><span  class='st_stumbleupon' ></span><span  class='st_delicious' ></span><span  class='st_email' ></span>";
$SETTINGS['PEN_COLOR'] = "bbd6FF";
$SETTINGS['PEN_DIAMETER'] = "5";
$SETTINGS['DEFAULT_ANNOTATION_WIDTH'] = "";
$SETTINGS['DEFAULT_ANNOTATION_HEIGHT'] = "";
$SETTINGS['DEFAULT_ANNOTATION_COLOR'] = "";
$SETTINGS['ANNOTATION_MARKER'] = "/images/schema/settings/ANNOTATION_MARKER.png";
$SETTINGS['ANNOTATION_MARKER_WIDTH'] = "11";
$SETTINGS['COPY_ACCESS'] = "4";
$SETTINGS['SETTINGS_ACCESS'] = "4";
$SETTINGS['AMBASSADOR_DISCOUNT'] = "15";
$SETTINGS['AMBASSADOR_SIGNUP_BONUS'] = "7";
$SETTINGS['AUTH_NET_LOGIN'] = "9vVCg9x9NDbB";
$SETTINGS['AUTH_NET_TRANS_KEY'] = "9gv89BH2kzD9BN9G";
$SETTINGS['AUTH_NET_TESTING'] = "1";
$SETTINGS['MAX_QUIZ_QUESTIONS'] = "4";
$SETTINGS['PASSING_GRADE'] = "70";
$SETTINGS['DEBUG'] = "1";
$SETTINGS['DEBUG_PAYMENT_USERNAME'] = "seller_1270929335_biz_api1.nomadcloud.com";
$SETTINGS['DEBUG_PAYMENT_PASSWORD'] = "MN64GXY28AH6KJTS";
$SETTINGS['DEBUG_PAYMENT_SIGNATURE'] = "AMY5u9K3Neb63qpiebkD1WWVOMAcAn0DjQ.ejcutesaMwvmQ.ZV2-1Xk";
$SETTINGS['PAYMENT_USERNAME'] = "adam.fisch_api1.gmail.com";
$SETTINGS['PAYMENT_PASSWORD'] = "4C5QGX659EA9VWWJ";
$SETTINGS['PAYMENT_SIGNATURE'] = "AFcWxV21C7fd0v3bYYYRCpSSRl31AC0VVbDAQQ1XNxBjSwp0Y9Uk67eK";
$SETTINGS['DEMO_TERM'] = "36";
$SETTINGS['ONE_MONTH_PRODUCT'] = "";
$SETTINGS['THREE_MONTH_PRODUCT'] = "";
$SETTINGS['ONE_YEAR_PRODUCT'] = "";
$SETTINGS['LIFETIME_PRODUCT'] = "";

?>